### ISSUE TITLE
Function mcrypt_module_open() is deprecated

### ISSUE THREAD

**Issue by hannesbochmann** [digedag/rn_base#102]
When I execute the unit tests with PHP 7.1 and TYPO3 8.7 I get the following deprecation notice:
PHP Runtime Deprecation Notice: Function mcrypt_module_open() is deprecated in /var/www/html/htdocs/typo3conf/ext/rn_base/Classes/Utility/Crypt.php line 135

**Comment by digedag** [comment]
Crypt will removed in next release. No support anymore.
