### ISSUE TITLE
PHP Error PHPUnit_Framework_TestCase not found

### ISSUE THREAD

**Issue by dominikmuellerwf** [digedag/rn_base#144]
I get the following error with PHP 7.2:
_Fatal error: Class 'PHPUnit_Framework_TestCase' not found in [...]/typo3conf/ext/rn_base/tests/class.tx_rnbase_tests_BaseTestCase.php on line 35_

It happens on TYPO3 8.7.26 with cfc_league (t3sports) while rendering a page with a plugin T3sports Ligaverwaltung.

**Comment by digedag** [comment]
I guess the error is more related to cfc_league_fe. Which plugin view do you use? Is your TYPO3 running in composer mode?

**Comment by digedag** [comment]
Should already be fixed.
