### ISSUE TITLE
Pagebrowser is not customizable

### ISSUE THREAD

**Issue by darthnorman** [digedag/rn_base#150]
There should be a way to wrap a single page browser item. It is not possible to create a structure like this:
```html
<ul class="pagebrowser">
<li><a href="#">preview</a></li>
<li><a href="#">current</a></li>
<li><a href="#">next</a></li>
</ul>
```
Currently the [ViewHelper](https://github.com/digedag/rn_base/blob/master/Documentation/fe_plugins.md#pagebrowser-viewhelper) is swallowing all code except child pagebrowser viewhelpers.

_Edit: ViewHelper hint added_

**Comment by rengaw83** [comment]
Just a workaround, but you can use the wrap argument of the PageBrowser.  
I have added a bootstrap pagination example to the [documentation](https://github.com/digedag/rn_base/blob/16f2314c0dfea4e5fb0ec1a2f4557e02312becd9/Documentation/fe_plugins.md#pagebrowser-viewhelper) in https://github.com/digedag/rn_base/commit/16f2314c0dfea4e5fb0ec1a2f4557e02312becd9.

**Comment by darthnorman** [comment]
I think you can close this issue, the wrap argument should do the trick.
