### ISSUE TITLE
9LTS: remove call to ExtensionManagementUtility::extRelPath() 

### ISSUE THREAD

**Issue by jpmschuler** [digedag/rn_base#154]
Having rn-base installed in a 9LTS and calling `vendor/bin/typo3cms language:update` results in an error thrown `Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'TYPO3\CMS\Core\Utility\ExtensionManagementUtility' does not have a method 'extRelPath' in` https://github.com/digedag/rn_base/blob/master/util/class.tx_rnbase_util_Extensions.php#L79

The [docs](https://api.typo3.org/typo3cms/8/html/deprecated.html#_deprecated000078) say  ExtensionManagementUtility::extRelPath is deprecated since TYPO3 v8, was removed in TYPO3 v9. `use PathUtility::getAbsoluteWebPath(), or ->siteRelPath()`. 

Didn't yet look into best way to solve this, just wanted to report this as early as possible.

**Comment by jpmschuler** [comment]
Nevermind, it was a 3rd-party ext using rn_base wrongly.

**Comment by digedag** [comment]
`extRelPath` was completly removed by TYPO3. It was primarly used to include resource files (JS,CSS) into backend. I think it makes no sense keep this method in rn_base as developers need to update backend stuff like TCA extensions or modules anyway.
Thank you raising this issue!
