### ISSUE TITLE
excludedParameters werden ignoriert

### ISSUE THREAD

**Issue by dmk-ralf-urban** [digedag/rn_base#155]
Betrifft TYPO3 9.5.8:

Wird rn_base z.B. in einer bestehenden Instanz hinzugefügt, die Parameter für den cHash ausgeschlossen hat, dann werden diese zukünftig ignoriert.
Bisherige Config in der LocalConfiguration.php
`    'FE' => [
        'cacheHash' => [
            'excludedParameters' => [
                   ....`
Dies wird mit rn_base ignoriert (oder überschrieben), die Parameter müssen neu gesetzt werden mit 
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']`

Bitte prüfen und beheben so dass auch die TYPO3-Standardkonfiguration erhalten bleibt.

**Comment by hannesbochmann** [comment]
Fehlender Support in Tx_Rnbase_Utility_Cache für TYPO3 9.5 dürfte die Ursache gewesen sein.
