### ISSUE TITLE
remove strict types and support php 5.6 again

### ISSUE THREAD

**Issue by rengaw83** [digedag/rn_base#159]
php 5.6 support are dropped in f5cca15b7258334b5ff6a889b5e7c3f6898610dd.
return type declarations are not supported for php 5.6 and should be removed.   
See [Environment.php#L105](https://github.com/digedag/rn_base/blob/d37c6e0d6c52553ba67f07b92a7570176321f03e/Classes/Utility/Environment.php#L105)

**Comment by Baachi** [comment]
I would agree with that, in our `composer.json` we require at least `php 5.6`. 

So we should either bump the php requirement to at least 7.0 (which means we need to drop typo3 6 support) or we must stay compatible with 5.6. 

For now i would prefer the second solution.

**Comment by digedag** [comment]
I also agree. It is not the time to drop 5.6 support. And not this way!
