### ISSUE TITLE
Please release a 9.5 compatible version to the TER

### ISSUE THREAD

**Issue by oliverklee** [digedag/rn_base#164]
Hi, in addition to the latest releases on Packagist, could you also please release to the TER so that installations in non-Composer mode can also use a 9LTS-compatible version of the extension?

(I propose to automatically release to TER when a new version is packaged. Please have a look at https://github.com/oliverklee/ext-oelib/blob/master/.travis.yml#L82 how to do this.)

**Comment by digedag** [comment]
Automatically TER release is very useful. Thanks for your link.
Next manually TER release will be done within the next few days!

**Comment by digedag** [comment]
First auto release to TER via Travis-CI was done! :champagne: :smirk: 
@oliverklee  Thank for suggestion!
