### ISSUE TITLE
Crash after update to version 1.11.1 due to missing ProcessorInterface

### ISSUE THREAD

**Issue by oliverklee** [digedag/rn_base#173]
On an installation, I first upgraded mkforms and then rn_base. After the update of rn_base to 1.11.1 (the latest version availble in the TER), the BE and the FE of the site were not available anymore due to this crash:

Uncaught TYPO3 Exception
#1476107295: PHP Warning: include(/home/www/p502259/html/typo3/typo3conf/ext/rn_base/Classes/Configuration/ProcessorInterface.php): failed to open stream: No such file or directory in /html/typo3/typo3_src-8.7.24/vendor/composer/ClassLoader.php line 444 (More information)

In case this extension follow semantic versioning, there must not be any breaking changes in a minor release (such as 1.11.0 after 1.10.x).

**Comment by digedag** [comment]
The missing interface is located in `/Legacy/classes.php`. If you don't use Composer mode try to refresh class loading information with `php typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation`.

Hope this helps.

**Comment by oliverklee** [comment]
Indeed, this was on a 8.7 installation without Composer mode. I'll try that. Thanks for the help!
