### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by stemeda** [digedag/rn_base#190]
I get this error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Sys25\RnBase\Utility\TYPO3\CMS\Core\Utility\GeneralUtility' not found | Error thrown in file/typo3conf/ext/rn_base/util/class.tx_rnbase_util_Files.php in line 51.`

I have no composet installation but I disabled and enabled the extension (rn_base, cfc_league and cfc_league_fe)

PHP 7.2
Typo3 8.7
rn_base from TER 1.12

**Comment by digedag** [comment]
Could you test it again? Should be fixed in master.
