### ISSUE TITLE
inline FAL elements can't be opened

### ISSUE THREAD

**Issue by mario-seidel** [digedag/rn_base#192]
Due to a change in handling of TCA palettes for inline FAL fields it's impossible to open them in TYPO3 lower version 9:
https://github.com/digedag/rn_base/blob/e22919fe32b6f74214fd12048c57bfc263f973da/util/class.tx_rnbase_util_TSFAL.php#L506

After comparing the two resulting arrays, I found the issue. The problem is the ending semicolon on this line. Remove it and it works like before (tested in TYPO3 8.7).

**Comment by digedag** [comment]
Thank's for this fix! :+1:
