### ISSUE TITLE
Pagebrowser not working anymore

### ISSUE THREAD

**Issue by darthnorman** [digedag/rn_base#194]
The link parameters changed:
rn_base 1.11.*: ?mktegut[pb-mknews-pointer]=1
rn_base 1.12.*: ?pb-mknews-pointer=1

**Comment by digedag** [comment]
Hi @darthnorman,
I cannot reproduce the issue in any of my plugins. Pagebrowser works in fine in 7.6 as well as in 10.4. I guess there is something wrong with your Typoscript configuration.

**Comment by hannesbochmann** [comment]
There is indeed a bug in rn_base. But only page browsers rendered with fluid are affected.
