### ISSUE TITLE
Crash after update to Version 1.12.6 due to missing ProcessorInterface

### ISSUE THREAD

**Issue by kludikovsky** [digedag/rn_base#203]
Following an update to version 1.12.6 in a Typo3 7.6.32 installation the system crashed with 
 
```
#1: PHP Warning: include(/var/www/html/public/typo3conf/ext/rn_base/Classes/Configuration/ProcessorInterface.php): failed to open stream: No such file or directory in /var/www/html/typo3_src-7.6.32/vendor/composer/ClassLoader.php line 444 (More information)
 ```

I followed the solution to the identical issue at https://github.com/digedag/rn_base/issues/173
but with no success and the following result.

 ```
php typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation

Uncaught TYPO3 Exception #1: PHP Warning: include(/var/www/html/public/typo3conf/ext/rn_base/Classes/Configuration/ProcessorInterface.php): failed to open stream: No such file or directory in /var/www/html/typo3_src-7.6.32/vendor/composer/ClassLoader.php line 444
thrown in file /var/www/html/typo3_src-7.6.32/typo3/sysext/core/Classes/Error/ErrorHandler.php
in line 111
```

The system (backend/frontend) is not operational now.

**Comment by digedag** [comment]
There are two important questions: Is your TYPO3 running in composer mode? How did you update the extension (ExtensionManager or composer update [in case of composer mode] or simple `git pull`)? 
You should also try to find the file that includes the **ProcessorInterface.php** file:
```bash
/var/www/html$ egrep -ir --include=*.php "(ProcessorInterface.php)" .
```

**Comment by kludikovsky** [comment]
This time it was running in non-composer mode and the update in TER Mode. So simply said, in conventional mode.

**Comment by digedag** [comment]
I close this issue because of missing requested information (files containing "ProcessorInterface.php"). 
Feel free to reopen if you have more info.
