### ISSUE TITLE
Fehlermeldung beim Update von 1.12.6 auf 1.13.3

### ISSUE THREAD

**Issue by entaxi57** [digedag/rn_base#205]
Hallo René,

beim Update von 1.12.6 auf 1.13.3 über TER erhalte ich die folgende Fehlermeldung:
'Could not scan for classes inside "/.../typo3conf/ext/rn_base/misc/" which does not appear to be a file nor a folder'

typo3 8.7
PHP 7.3

**Comment by oliverklee** [comment]
@entaxi57 Ist deine Installation Composer-basiert oder klassisch?

**Comment by entaxi57** [comment]
Hallo Oliver,

meine Installation ist klassisch.

Bernd

**Comment by hannesbochmann** [comment]
Der Ordner wurde entfernt und kommt auch nirgends mehr vor. Bisher stand er im Autoloading drin, nun aber nicht mehr. Hast du mal direkt vor dem Installieren die Caches geleert?

**Comment by entaxi57** [comment]
Hallo Hannes,

ich habe es gerade noch einmal getestet und vorher die Caches geleert. Leider erhalte ich die Fehlermeldung weiterhin.

Die Anwendung scheint aber zu funktionieren bzw. bisher konnte ich keinen Fehler bei cfc_league finden.

Bernd

**Comment by digedag** [comment]
Also da diese Probleme immer wieder auftreten und ich auch in Zukunft weitere alte Klassen in den PSR-4 Namespace verschieben werde, hab ich mir mal geschaut, was TYPO3 da im **Nicht**-Composer-Modus genau treibt.

Wenn ich das richtig sehe, schreibt TYPO3 die Informationen zum Classloading analog zum Composer in normale PHP-Dateien raus. Diese liegen dann im Verzeichnis **typo3conf/autoload/**. Wenn man das Update an TYPO3 vorbei macht, dann bekommt TYPO3 natürlich auch nicht mit, daß die Dateien neu erzeugt werden müssen.

Mögliche Lösungen wären dann folgende:

### TYPO3 7.6 und 8.7

1. eine beliebige Extension im ExtensionManager deaktivieren und dann wieder aktivieren
2. das Verzeichnis **typo3conf/autoload/** komplett löschen

Bei Variante 1 wird auf jeden Fall der Event ausgelöst, der TYPO3 zum Re-Dump der Dateien animiert. Variante 2 nutzt die Tatsache, daß TYPO3 beim Bootstrap das Vorhandensein des Verzeichnisses prüft. Sollte es fehlen wird es automatisch angelegt (Schreibrechte sicherstellen!) und die Classloading-Dateien werden neu erstellt.

### ab TYPO3 9

Ab TYPO3 9 gibt es wieder ein Command, das die Classloading-Dateien neu erzeugt. Dafür einfach auf der Kommandozeile folgenden Befehl ausführen:

```bash
$ vendor/bin/typo3 extension:dumpclassloadinginformation
```

Ich hoffe, das hilft weiter. :slightly_smiling_face:

**Comment by entaxi57** [comment]
Hallo René,

leider hat beides bei mir nicht geklappt. Die Fehlermeldung wurde immer wieder angezeigt.

Ich habe es aber jetzt wie folgt durchgeführt:
1. Update von 1.12.6 auf 1.13.3 über TER - Fehlermeldung wird angezeigt. Probleme mit der Anwendung kann ich aber bisher nicht feststellen.
2. Update von 1.13.3 auf 1.13.4 über TER - Fehlermeldung wird nicht mehr angezeigt. Probleme mit der Anwendung kann ich ebenfalls bisher nicht feststellen.

Werde es noch weiter beobachten.

Bernd

**Comment by digedag** [comment]
Hallo Bernd,
laß uns der Sache doch mal auf den Grund gehen. Daß du keine weiteren Fehler hast, liegt daran, daß in dem Ordner keine Klassen waren, die in Verwendung sind. Nachdem du beide Vorschläge ausprobiert hast, sollten wir mal der Reihe nach vorgehen.

Die Quelle für den Order "misc" ist die `composer.json` im Verzeichnis **typo3conf/ext/rn_base/**. Kann du da bitte mal nachschauen und sicherstellen, daß da im Abschnitt `autoload/classmap` der Ordner **misc/** nicht mehr drin steht?

Und dann würde mich noch interessieren, wann und wo genau die Fehlermeldung erscheint und ob du eventuell auch noch irgendwo einen Stacktrace finden kannst?

**Comment by entaxi57** [comment]
Hallo René,

der Order "misc" ist nicht mehr im Abschnitt autoload/classmap in der composer.json enthalten.

Die Fehlermeldung erscheint bei Beendigung des Updates. Leider kann ich sonst nichts mehr finden.

Bernd

**Comment by digedag** [comment]
Was bedeutet genau "bei Beendigung des Updates"? Du bist im ExtensionManager, oder? Eventuell werden da nochmal irgendwo die Daten aus der composer.json gecached. Gibt es die Fehlermeldung eventuell auch im Ereignis-Log? Vielleicht stehen da noch zusätzliche Infos...

**Comment by entaxi57** [comment]
Hallo René,

ich habe jetzt noch einmal folgende Schritte ausgeführt:

1. Installation der alten Version 1.12.6 über "Erweiterungen hochladen" des ExtensionManager. Ordner misc/ ist jetzt in der composer.json vorhanden.
2. Eine Extension deaktiviert und wieder aktiviert.
3. Cache geleer.
4. Aktuallierung der neuen Version 1.13.4 über den ExtensionManager ausgeführt. Extension ist aktiviert und die Fehlermeldung wird angezeigt. Ordner misc/ ist jetzt nicht mehr in der composer.json vorhanden. Im Ereignis-Log wird nichts angezeigt.
5. Wieder Punkt 1 ausgeführt.
6. Verzeichnis typo3conf/autoload/ gelöscht.
7. Cache geleer.
8. Aktuallierung der neuen Version 1.13.4 über den ExtensionManager ausgeführt. Extension ist aktiviert und die Fehlermeldung wird angezeigt. Ordner misc/ ist jetzt nicht mehr in der composer.json vorhanden. Im Ereignis-Log wird nichts angezeigt. Verzeichnis typo3conf/autoload/ wurde neu erzeugt.

Bernd

**Comment by digedag** [comment]
Also wenn ich das richtig verstehe, dann kommt die Fehlermeldung nur genau bei dem Schritt, wenn du von der alten Version 1.12.6 auf die neue Version 1.13.4 wechselst. Kommt denn die Fehlermeldung auch nochmal, wenn du bereits auf der neuen Version bist? Also da nochmal den autoload-Ordner löschen oder eine andere Extension aktualisieren?
Wenn nicht, dann gibt es auch kein Problem. Dann kommt die Fehlermeldung beim Update vermutlich daher, daß bei diesem Schritt noch die Paketinformationen der alten Version geladen sind. Das wäre dann ein Bug in TYPO3, aber der ist nicht weiter dramatisch. Danach einmal den Autoload neu laden und alles ist in Ordnung.

Wenn du das aber regelmäßig weiterhin bekommst, dann müssten wir weiter suchen, wo TYPO3 den Hinweis auf den alten Ordner noch herbekommt. Aber das kann ich mir nicht vorstellen.

**Comment by entaxi57** [comment]
Hallo René,

die Fehlermeldung kommt nur beim Update von der alten Version 1.12.6 auf die neue Version 1.13.4. Die Fehlermeldung auch nicht noch einmal, wenn ich bereits auf der neuen Version bin. Ich kann auch problemlos den autoload-Ordner löschen bzw. andere Extension aktualisiere. 

Ich hatte auch mal ein Update von 1.12.6 auf 1.13.3 gemacht (mit Fehlermeldung). Danach hatte ich dann das Update 1.13.3 auf 1.13.4 gemacht (ohne Fehlermeldung). Der Autoload wurde dadurch neu geladen.

Die Extension läuft einwandfrei. Also kann das Ticket von meiner Seite wieder geschlossen werden.

Bernd

**Comment by digedag** [comment]
Okay. Danke für die Geduld und Unterstützung! :+1:
