### ISSUE TITLE
non backward compatible change (Autodetect usealias in SearchBase) since version 1.13.5

### ISSUE THREAD

**Issue by hannesbochmann** [digedag/rn_base#206]
The commit [44da2028c201bf8efac1aec3e72444fc3a0e7553](https://github.com/digedag/rn_base/commit/44da2028c201bf8efac1aec3e72444fc3a0e7553) may break the functionality of old search classes. An example is mksearch. [tx_mksearch_search_Index](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/master/search/class.tx_mksearch_search_Index.php) returns a base table alias but aliases were never used. This changed now which causes the joins to break because no alias is used there.

**Comment by digedag** [comment]
This means, mksearch should stay at 1.12.x or fix the misusage of getBaseTableAlias().

**Comment by digedag** [comment]
You could also override `useAlias()` and return `false` to force the former behavior... :wink:
