### ISSUE TITLE
1.13.5 is no longer compatible with TYPO3 7.6

### ISSUE THREAD

**Issue by osw-mw** [digedag/rn_base#207]
Exception when calling Sys25\RnBase\Database\Connection::doSelect:

Classname contains invalid characters or has invalid format: TYPO3\CMS\Core\Database\ConnectionPool 

27 tx_rnbase::getClassInfo("TYPO3\CMS\Core\Database\ConnectionPool", "")

/.../htdocs/typo3conf/ext/rn_base/class.tx_rnbase.php:

00324:     private static function _findT3($minimalInformation, $alternativeKey = '', $prefix = 'class.', $suffix = '.php')
00325:     {

00326:         $info = self::getClassInfo($minimalInformation, $alternativeKey);

00327: 
00328:         return $info['path'];

26 tx_rnbase::_findT3("TYPO3\CMS\Core\Database\ConnectionPool", "", "class.", ".php")

/.../htdocs/typo3conf/ext/rn_base/class.tx_rnbase.php:

00180:         }
00181: 

00182:         $path = self::_findT3($minimalInformation, $alternativeKey, $prefix, $suffix);

00183: 
00184:         if ($path) {

25 tx_rnbase::loadT3("TYPO3\CMS\Core\Database\ConnectionPool")

/.../htdocs/typo3conf/ext/rn_base/class.tx_rnbase.php:

00054:         }
00055: 

00056:         if (self::loadT3($classNameOrPathInformation)) {

00057:             self::$loadedClasses[$classNameOrPathInformation] = true;
00058: 

24 tx_rnbase::load("TYPO3\CMS\Core\Database\ConnectionPool")

/.../htdocs/typo3conf/ext/rn_base/class.tx_rnbase.php:

00087:     {
00088:         $ret = false;

00089:         if (self::load($class)) {

00090:             self::load('tx_rnbase_util_Typo3Classes');
00091:             $utility = tx_rnbase_util_Typo3Classes::getGeneralUtilityClass();

23 tx_rnbase::makeInstance("TYPO3\CMS\Core\Database\ConnectionPool")

/.../htdocs/typo3conf/ext/rn_base/Classes/Database/QueryBuilderFacade.php:

00151:     private function getConnectionPool(): ConnectionPool
00152:     {

00153:         return \tx_rnbase::makeInstance(ConnectionPool::class);

00154:     }
00155: }

22 Sys25\RnBase\Database\QueryBuilderFacade::getConnectionPool()

/.../htdocs/typo3conf/ext/rn_base/Classes/Database/QueryBuilderFacade.php:

00059:         // $union = is_string($arr['union']) > 0 ? $arr['union'] : '';
00060: 

00061:         $queryBuilder = $this->getConnectionPool()->getQueryBuilderForTable($tableName);

00062:         $queryBuilder->selectLiteral($what) // TODO: use selectLiteral on demand only
00063:             ->from($tableName, $tableAlias != $tableName ? $tableAlias : null);

21 Sys25\RnBase\Database\QueryBuilderFacade::doSelect("*", Sys25\RnBase\Database\Query\From, array)

/.../htdocs/typo3conf/ext/rn_base/Classes/Database/Connection.php:

00124: 
00125:         $qbFacade = new QueryBuilderFacade();

00126:         $queryBuilder = $qbFacade->doSelect($what, $from, $arr);

00127: 
00128:         if ($queryBuilder) {

20 Sys25\RnBase\Database\Connection::doSelect("*", Sys25\RnBase\Database\Query\From, array, boolean)

/.../htdocs/typo3conf/ext/mkforms/dh/db/class.tx_mkforms_dh_db_Main.php:

00422:         $options['enablefieldsoff'] = 1;
00423:         $options['where'] = $sKeyname.' = '.Tx_Rnbase_Database_Connection::getInstance()->fullQuoteStr($iUid, $sTablename);

00424:         $ret = Tx_Rnbase_Database_Connection::getInstance()->doSelect($sFields, $sTablename, $options, 0);

00425: 
00426:         return count($ret) ? $ret[0] : false;

**Comment by osw-mw** [comment]
QueryBuilderFacade is new in 1.13.0. Version 1.12.6 still works with TYPO3 7.6.

**Comment by digedag** [comment]
Thanks for reporting the issue. Could you test the fix? It should disable querybuilder in 7.6.

**Comment by osw-mw** [comment]
Thanks for looking into it. I can confirm that the version check fixes the problem.
