### ISSUE TITLE
Uncaught TYPO3 Exception: Call to undefined method tx_rnbase_util_TYPO3::isTYPO42OrHigher()

### ISSUE THREAD

**Issue by entaxi57** [digedag/rn_base#208]
Hallo René,

wenn ich über das Backend "T3sports - Wettbewerde verwalten" aufrufe, bekomme ich folgende Fehlermeldung:
 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method tx_rnbase_util_TYPO3::isTYPO42OrHigher() | Error thrown in file /typo3conf/ext/cfc_league/Classes/Controller/Team.php in line 119. Requested URL: ...?M=web_CfcLeagueM1&moduleToken=--AnonymizedToken--&id=982

Es ist auch nicht mehr möglich, "T3sports" aufzurufen.
 
TYPO3: 8.7
php 7.3
rn_base: 1.13.8, **mit der 1.13.5 funktioniert es noch**
cfc_league: 1.6.1
cfc_league_fe: 1.6.1

**Comment by digedag** [comment]
Du solltest auch cfc_league und cfc_league_fe aktualisieren.

**Comment by entaxi57** [comment]
Hallo René,

danke für den Hinweis.

cfc_league und cfc_league_fe habe ich jetzt auch aktuallisiert. Jetzt klappt es.

p.s. Ich hatte rn_base über TER aktuallisiert. Da waren aber die neuen Versionen von cfc_league und cfc_league_fe nicht vorhanden.

Bernd

**Comment by digedag** [comment]
Danke für den Hinweis. Das TER hatte ich gar nicht mehr auf dem Schirm. Da hatte letztens der Build nicht funktioniert. Ich schieb das gleich nochmal an! :slightly_smiling_face:
