### ISSUE TITLE
Drop support for TYPO3 7.6

### ISSUE THREAD

**Issue by oliverklee** [digedag/rn_base#253]
The extension is not installable with TYPO3 7.6 (at least not in Composer mode) because the Git subtree split happened with TYPO3 8.7.

Also, the class loading is broken in TYPO3 8.7 as some classes cannot be loaded.

This has been discovered while trying to get the unit tests to run on CI again: https://github.com/digedag/rn_base/pull/252/checks?check_run_id=3892408984

Also, 7LTS and 8LTS have been moved out of public support for quite some time.

I propose dropping support for TYPO3 7LTS and 8LTS as those have been broken anyway for rn_base (at least since the big refactorings of the 1.14 version).

@digedag What do you think?

**Comment by digedag** [comment]
The drop will come for version 1.5. And I think 1.5 will come in near future. 1.4.0 isn't really stable. There will be a 1.14.1 and then we should go to 1.5.0.

**Comment by digedag** [comment]
@oliverklee I would like to tag 1.4.1. Is it okay for you?

**Comment by oliverklee** [comment]
@digedag Yes, please do so. Thank you!

**Comment by oliverklee** [comment]
@digedag Thanks for the release!

Could you also please publish the new version to the TER? (My seminars extension needs to work in non-Composer mode as well, which means that all dependencies also need to be available via the TER in addition to on Packagist.) Thanks! :heart:

**Comment by digedag** [comment]
@oliverklee Autodeployment has gone with TravisCI. It wasn't replaced by Github action until now. I created #267 and I saw you already did this in seminars. I will have a look at this next friday.

**Comment by digedag** [comment]
Close ticket as fixed.
