### ISSUE TITLE
Provide TER release task in build pipeline

### ISSUE THREAD

**Issue by digedag** [digedag/rn_base#267]
TER release via TravisCI should be replaced by Github action job.

**Comment by oliverklee** [comment]
You can copy the tailor-based solution from https://github.com/oliverklee/ext-phpunit/blob/main/.github/workflows/release.yml .
You'll need to create an authentication token at https://extensions.typo3.org/ and set it as the `TYPO3_API_TOKEN` secret in the GitHub repository settings.
Optionally, you can `prepare-release`  Composer script to remove unwanted stuff before release: https://github.com/oliverklee/ext-phpunit/blob/main/composer.json#L94

With that, you're ready to release. :-)

**Comment by oliverklee** [comment]
(The way I'm doing it in seminars is outdated: Tailor is the currently recommended way, and using the ready-made GitHub action (like in phpunit) is the easiest way to use it.)

**Comment by digedag** [comment]
Thanks for support! Version 1.14.2 is now released to TER.
