### ISSUE TITLE
Add support for TYPO3 11.5 LTS

### ISSUE THREAD

**Issue by rengaw83** [digedag/rn_base#292]

**Comment by digedag** [comment]
@rengaw83 I renamed branch `11.5` to `upgrade/11.5`. When do you think it will be possible to merge changes to master? Do you expect any complications?

**Comment by hannesbochmann** [comment]
@digedag In the moment I'm working on a big upgrade project. I'm still running into problems with TYPO3 11.5 and more so with PHP 8.0. But I'm confident that most things in rn_base will be made compatible towards the end of this upgrade project. So I would say in 2-3 weeks the changes can be merged into the master.

**Comment by rengaw83** [comment]
I only have changed backend related things. At the moment i only have in use some old extensions with be modules.
Renaming the branches is okay, but you have to fix the `branch-alias` in `composer.json` to @digedag.

**Comment by stigfaerch** [comment]
> @digedag In the moment I'm working on a big upgrade project. I'm still running into problems with TYPO3 11.5 and more so with PHP 8.0. But I'm confident that most things in rn_base will be made compatible towards the end of this upgrade project. So I would say in 2-3 weeks the changes can be merged into the master.

What is the status?

**Comment by hannesbochmann** [comment]
Many problems should be fixed right now. At least the project I was talking about is almost done and running with rn_base without problems.

**Comment by derhecht** [comment]
Hallo @digedag ,
als Admin von bistumsliga.de sind wir durch unseren Hoster mehr oder minder gezwungen auf TYPO3 11 zu migrieren. Kann ich als Entwickler irgendwie unterstützen, dass rn_base, cfc_league und cfc_league_fe dafür kompatibel wird? Bzw. wo siehst du ggf. den Besten Ansatzpunkt dafür?

**Comment by digedag** [comment]
@derhecht Am Freitag tagge ich rn_base mit Support für T3 11. Danach rechne ich spätestens Ende der kommenden Woche mit Versionen für T3sports. Das Backend funktioniert schon. :slightly_smiling_face:
