### ISSUE TITLE
function parameter in tx_rnbase_util_Misc::callHook() has wrong type

### ISSUE THREAD

**Issue by darthnorman** [digedag/rn_base#293]
TYPO3 10.4
rn_base 1.13.*

The fourth parameter of tx_rnbase_util_Misc::callHook() should be null or an object
https://github.com/digedag/rn_base/blob/089fb322e5583f917832a9bc67977b7328333e29/Classes/Utility/Misc.php#L118

otherwise it will trigger this deprication error:

_"$ref" is of type "integer" which is deprecated since TYPO3 10.3. "$ref" must be of type "object" or null as of version 11.0'_

./htdocs/typo3/sysext/core/Classes/Utility/GeneralUtility.php

**Comment by digedag** [comment]
Fixed for 1.15.x
There will be no support for TYPO3 11 in 1.13.x.
