### ISSUE TITLE
Classname contains invalid characters or has invalid format: Sys25\RnBase\Fluid\View\Action

### ISSUE THREAD

**Issue by nwm-dev** [digedag/rn_base#296]
Bear with me as I haven't worked with this extension so far. I upgraded a typo3 instance from v9 to v10 and one view depending on this extension threw the above error. After some digging and testing it turned out changing the use in `EXT:rn_base/Legacy/Controller/AbstractController.php`

 from `use Sys25\RnBase\Fluid\View\Action`

to `use Sys25\RnBase\ExtBaseFluid\View\Action`

fixed the error. To me it seems like an oversight while moving the Class to a new namespace. If someone could verify this who is more familiar with the extension I can create a PR if necessary.

**Comment by dzschille** [comment]
I got a similar Message (found with MK Logger):
`"Classname contains invalid characters or has invalid format: Sys25\\RnBase\\Fluid\\View\\Action"`.

This came from my TS Config of mksearch which i added as [here suggested](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/issues/62#issuecomment-534667289):
`viewClassName = Sys25\RnBase\Fluid\View\Action`

I changed that to `viewClassName = Sys25\RnBase\ExtBaseFluid\View\Action`. This solved the error message.

Later i also had to change in some templates `{namespace rn=Sys25\RnBase\Fluid\ViewHelper}` to `{namespace rn=Sys25\RnBase\ExtBaseFluid\ViewHelper}`.
