### ISSUE TITLE
Proposal: Add ArrayAccess Interface to DataModel

### ISSUE THREAD

**Issue by hannesbochmann** [digedag/rn_base#297]
Since TYPO3 9.5 there is a problem with Fluid and the magic getter methods of models inheriting Sys25\RnBase\Domain\Model\DataModel. Those magic methods will no longer be called in a Fluid template since the existence of the methods is checked with methods_exists() and not anymore with is_callable(). There is a longer discussion (https://github.com/TYPO3/Fluid/issues/513) why this won't be changed again. 
A proposed solution is to implement the ArrayAccess interface in the desired object. In the moment I see no drawbacks in introducing the interface in Sys25\RnBase\Domain\Model\DataModel.

@rengaw83 @digedag What do you think about that?

**Comment by rengaw83** [comment]
In 2022 and since we all use strict types, return types, etc. we should not use this magic methods any more and should add a method for reach property:
```php
class Model extends BaseModel {
    public function getDescription(): string {
        return $this->getProperty('description') ?? '';
    }
}
```
All other "magic" implementations are just workarounds to avoid having to modernize legacy code.

**Comment by hannesbochmann** [comment]
I'm completely with you. I wouldn't use magic methods in new code. Nevertheless there are a lot of legacy projects which could need this backwards compatibility. If this proposal get's rejected It's fine. The necessary changes can also be implemented in legacy projects via patch etc.

**Comment by digedag** [comment]
Hab ich grundsätzlich kein Problem damit. Also das ArrayAccess-Interface sollte ja eh keine Schwierigkeiten verursachen. Und die MagicMethods sehe ich eher als Nice2Have. Ich hab sie in meinen Projekten nie aktiv genutzt. Ich hab eher die Erfahrung gemacht, daß sie Fehler verdecken. 
Allerdings meine ich, daß sie auch im Zusammenspiel mit Twig genutzt werden. Wenn sie im BaseModel entfernt werden, könnte man sie eventuell auch per Trait bereitstellen. Wer sie unbedingt benötigt, kann dann zumindest den Trait nutzen.

**Comment by hannesbochmann** [comment]
@digedag Dir wäre es also lieber wenn nur ein Trait bereitgestellt wird?

**Comment by digedag** [comment]
@hannesbochmann Welchen konkreten Grund gibt es denn, die Magic-Methods zu entfernen? Nur die Tatsache, daß sie in Fluid nicht genutzt werden können, kann ja eigentlich kein Grund sein. Die Methoden gab es auch schon vor Fluid. Und mit Twig können sie auch immer noch genutzt werden. Außerdem kann man den Models bei Bedarf auch, wie vorgeschlagen, extra Getter hinzufügen, wenn die für Fluid notwendig sind. (Wobei da vermutlich ein "Helper" für den Zugriff über getProperty() einiges an Arbeit ersparen würde. Aber keine Ahnung, was da in Fluid sinnvoll und möglich ist.)
 
Also, wenn es einen trifftigen Grund gibt sie zu entfernen, weil sonst irgendetwas nicht mehr funktioniert, dann hätte ich nichts dagegen. Falls nicht, dann können sie doch drin bleiben.

**Comment by hannesbochmann** [comment]
@digedag Die Magic-Methoden sollen doch gar nicht entfernt werden. Ich möchte nur das ArrayAccess Interface implementieren.

**Comment by digedag** [comment]
@hannesbochmann Warum diskutieren wir denn dann darüber?? :laughing: 
Gegen das Interface spricht ja nix...
