### ISSUE TITLE
Add support for TYPO3 12.x

### ISSUE THREAD

**Issue by digedag** [digedag/rn_base#310]
- [x] Allow install
- [x] Fix module router
- [x] Fix link generation in backend
- [x] Fix legacy db access

**Comment by digedag** [comment]
Also die TSConfig wurde da nicht geladen. Es wurde lediglich das MCONF-Array übernommen. Das passierte bisher doppelt, weil es auch schon in der init() drin war. Somit wurde nur der doppelte Aufruf entfernt. Und den ModuleRunner gibt es ab T3 8 nicht mehr, somit konnte der auch weg. 
Tendenziell hätte ich das erste Release mit TYPO3 12 Support eh mit 1.17. getaggt. Aber die Tags werden ja recht schnell rausgehauen... :wink: 

Ansonsten aber das Problem in mklog lösen. Die Module funktionieren grundsätzlich. Ich check den Umbau in allen T3 Versionen.

**Comment by hannesbochmann** [comment]
Ja, mit dem Tag war ich etwas voreilig. Sorry. Habe jetzt mklog entsprechend angepasst. (https://github.com/DMKEBUSINESSGMBH/typo3-mklog/issues/25)

**Comment by digedag** [comment]
@hannesbochmann ich hab jetzt mal einen Maintenance-Branch für die 1.16 erstellt und neu mit 1.16.8 getagged. Die Änderungen für TYPO3 12 sind da raus. Eventuell musst du das BE-Modul von mklog nochmal prüfen. Aber vermutlich wird es trotzdem funktionieren. Sonstige Änderungen, die für die 1.16. notwendig wären, habe ich nicht gefunden. Falls doch, dann ab jetzt im Maintenance-Branch ergänzen und taggen.

Im Master wird nun für die 1.17 mit Support für TYPO3 12 entwickelt. Ich hoffe, damit gibt es zukünftig weniger Probleme.
