### ISSUE TITLE
Incompatible with PHP 7 since 1.16.7 (Constructor property promotion not supported)

### ISSUE THREAD

**Issue by rengaw83** [digedag/rn_base#312]
https://github.com/digedag/rn_base/blob/a453b0f6a931f110cd3f133d082d7cbe4b69a9e4/Classes/Backend/Module/ModFuncFrame.php#L53-L58

Constructor property promotion is not supported in PHP 7.

**Comment by rengaw83** [comment]
`"phpcompatibility/php-compatibility": "^9.3.5"` does not support php 8! 

`^10@dev` has some php 8 rules, including the `NewConstructorPropertyPromotionSniff`.  
Maybe you should switch to this dev version until a new compatible version is released.  
Otherwise the PHPCompatibility checks ere untruthfully.

**Comment by digedag** [comment]
Ich verstehe das Problem nicht. Die Klasse wird ausschließlich unter TYPO3 12 verwendet. TYPO3 12 verlangt mindestens PHP 8.1. Also kann man hier auch alle Features von 8.1. nutzen.
Die Tests in der Pipeline habe ich entsprechend modifiziert. Durch das Tag @php81 werden die entsprechenden Klassen bei den Tests mit PHP < 8.0 gefiltert. Und bei den 8.1/8.2 Tests funktioniert der Check.

**Comment by rengaw83** [comment]
Siehe Kommentar in https://github.com/digedag/rn_base/commit/4e76b77e46e8244b4cfc48720f269584db01b17f#r109764725

Die Klasse ist in der Service.yaml als Public-Service für die DI registriert und die Datei wird damit unweigerlich für den Warmup geladen und crashed den PHP-Prozess durch Parser-Errors.

**Comment by digedag** [comment]
Ah, verstehe. Ja, das ist ein Argument. Das wird sich auch nicht umgehen lassen. Dann muss ich das noch mal umbauen. Danke für den Hinweis!

**Comment by digedag** [comment]
Der Konstruktor passt nun wieder.
