### ISSUE TITLE
Error after install in TYPO3 12.4.4

### ISSUE THREAD

**Issue by REYGERS-Systemhaus** [digedag/rn_base#322]
Hi,

after installing the extension in TYPO 12.4.4 I got the folowing error:
![image](https://github.com/digedag/rn_base/assets/123623568/36033c2b-c41f-40c4-a808-37f1646e0cca)

**Comment by digedag** [comment]
This is a class path issue. Do you run with or without composer? If not, is it a first install of rn_base or an update?

**Comment by REYGERS-Systemhaus** [comment]
I installed it without composer. It was the first install of rn_base.

**Comment by digedag** [comment]
I pushed version 1.17.2 to TER. This should fix the issue.

**Comment by REYGERS-Systemhaus** [comment]
Yes, it works now! Thank you very much!
