### ISSUE TITLE
BE Module ab TYPO3 12

### ISSUE THREAD

**Issue by hannesbochmann** [digedag/rn_base#331]
@digedag Es gab ja schon einige Änderungen, damit BE Module ab TYPO3 12 noch funktionieren. Allerdings ist mir nicht klar, ob schon alles funktioniert und wie der Migrationspfad aussieht. Ich möchte z.B. gerade das BE Modul von mksearch mit TYPO3 12 kompatibel machen. Wenn ich es richtig verstehe, kann das Hauptmodul entfallen und ich brauche nur noch die Submodule, die ich per Configurations/Backend/Modules.php registrieren. Oder ist das falsch?
Und mir scheint als müsste \Sys25\RnBase\Backend\Module\ExtendedModFunc noch ähnlich wie \Sys25\RnBase\Backend\Module\BaseModFunc erweitert werden, um in TYPO3 12 zu funktioniren. Ist das richtig? 

Sind ansonsten Änderungen zu erwarten? Müssen z.B. Templates angepasst werden, damit die Submodul-Menüs korrekt gerendert werden?

Ich bin für jeden Hinweis dankbar, da du sicherlich schon ein BE Mpdul auf Basis von rn_base in TYPO3 12 eingerichtet hast.

**Comment by hannesbochmann** [comment]
Da hast du sicherlich recht, dass die ExtendedModFunc nicht mehr die beste Lösung ist. Aber an sich funktioniert das noch immer problemlos. Und eine Migration wäre bei mksearch relativ aufwendig. Daher habe ich ein paar Fixes eingefügt, womit die ExtendedModFunc auch in TYPO3 12 funktioniert. In mksearch musste ich aber trotzdem einige Anpassungen vornehmen.

Ich habe einen Pull Request erstellt und würde dir die Entscheidung überlassen, ob du den Fix mit drin haben willst.

**Comment by digedag** [comment]
Also wenn die ExtendedModFunc eigentlich nicht benötigt wird, dann sollte sie zumindest als `deprecated` annotiert werden. Das kannst du ja in deinem MR noch machen. Ansonsten kannst du die Änderungen gerne mergen.
