### ISSUE TITLE
Reformat code base to PSR-2

### ISSUE THREAD

**Issue by oliverklee** [digedag/rn_base#38]
I'd be willing to reformat the code bases of rn_base, mk_forms and mklib (and possible other extensions as needed) to PSR-2 (using the php-cs-fixer with the same setting as for the TYPO3 Core). Would this be okay, and would you be willing to merge those PRs?

**Comment by oliverklee** [comment]
(Then the code would have the same style as the current TYPO3 Core.)

**Comment by digedag** [comment]
PSR-2 says _Code MUST use 4 spaces for indenting, not tabs_. 
We use tabs for indending and everyone can choose an individual tab width. So the answer is no. I will not merge a lot of annyoing spaces into my code. :no_entry_sign:
