### ISSUE TITLE
phpunit testcases should run stand alone

### ISSUE THREAD

**Issue by rengaw83** [digedag/rn_base#43]
The phpunittests should run completly without the typo3 core or the tx_phpunit extension.

ToDo's:
- [ ] extend from `PHPUnit_Framework_TestCase` instead of `Tx_Phpunit_TestCase`
- [ ] refactor `tx_rnbase_tests_BaseTestCase::BaseTestcase` to work without `Tx_Phpunit_AccessibleProxy` and `Tx_Phpunit_Interface_AccessibleObject`

**Comment by oliverklee** [comment]
You'll always need the TYPO3 Core for this: Even if you mock the Core classes, you'll still need the classes as base classes for the mocks.

**Comment by digedag** [comment]
The core of TYPO3 is needed for sure. But we don't want to run the tests inside a TYPO3 environment. The tests should run with vanilla phpunit on command line.

**Comment by rengaw83** [comment]
The TYPO3 core is not absolutely necessary for the unittests. 

In the true sense of unittests, each method is tested individually, with no real additional calls. So there is - strictly seen - no need for the core.

But i admit that it will be easier for many tests with the core.

**Comment by rengaw83** [comment]
The first tests are adapted in 575eee638d5331e17334ec7573c3e0276c274d28 and the `.travis.yml` was added in 58b309e7b98082e428141e01b14cf154ddaaad1f.

All tests in group `unit` can be tested now automatically by the Travis-CI
```php
/**
 * @group unit
 * @test
 */
```
@digedag can you add this repo to your https://travis-ci.org/ account please?

**Comment by digedag** [comment]
Unittests already run on travis. So I close this ticket.
