### ISSUE TITLE
use tx_rnbase_parameters::getCleaned() as default for tx_rnbase_parameters::get()

### ISSUE THREAD

**Issue by hannesbochmann** [digedag/rn_base#45]
In rare cases this might break an application but in most cases this will close security vulnerabilities. That's why I think by default all parameters should be returned cleaned with the possibility to prevent this.

What do you think?

**Comment by oliverklee** [comment]
removeXSS taugt nichts (siehe https://review.typo3.org/#/c/48102/), und das Escapen/Enkodieren muss kontextabhängig geschehen, also beim einbauen in HTML, JSON, JavaScript, SQL etc., nicht schon beim Holen.

**Comment by oliverklee** [comment]
Bei getCleaned ist mir aber auch nicht ganz klar, ob es dabei um Filtern, Validieren oder Enkodieren geht.

**Comment by digedag** [comment]
Das Thema hatten wir schon vor ein paar Jahren. Und auch da stand am Ende die Meinung, daß letztendlich der Extension-Entwickler für die saubere Verarbeitung der Parameter verantwortlich ist. Wenn man versucht diese Verantwortung zu verschieben, dann bringt das nur eine trügerische Sicherheit mit sich.
Lassen wir es also lieber so, wie es ist.
