### ISSUE TITLE
function get() returns null instead of array or string in class.tx_rnbase_configurations.php

### ISSUE THREAD

**Issue by RocKordier** [digedag/rn_base#48]
[class.tx_rnbase_configurations.php#L415](https://github.com/digedag/rn_base/blob/1e74ddf4d23b076366f65c893a134058246b2128/class.tx_rnbase_configurations.php#L415)

If there is no ts for a given pathKey `public function get()` returns null instead of an empty array.

@rengaw83 is there any reason for that?

**Comment by rengaw83** [comment]
Typisches verhalten. Eher ein Feature in rn_base als ein Bug.

Ich nehme an du willst direkt auf ein Array zugreifen:
->get('confid.') und erwartest ein Array.
Das configurations Objekt greift dabei auf das TS zu, ist dieser Note nicht gesetzt. Bekommst du NULL. 
Das ist keine Eigenart, sondern auch beim Zugriff auf Arrays "$array['confid']" oder nicht existierende properties "$obj->confid" so.

An diesem verhalten würde ich nichts ändern, dies kann an einigen Stellen erforderlich sein.

Entweder du castest es "(array) $conf->get('confid.')", prüfst den Wert gegen "===NULL" und korrigierst ihn, oder es wird eine neue Methode ala "getArray ()" im configurations Objekt gebaut, die bei 'confid' an "getExploded" weiterleitet und bei 'confid.' (with dot) den Rückgabewert auf ein Array hin prüft und im Zweifelsfall ein leeres liefert.
Ggf. kann auch getExploded gleich refactored werden.

In deinem Fall kannst du auf die schnelle nen cast machen oder getExploded nutzen.
Zwei mal get aufrufen würde ich nicht machen, das is bei verschachtelten TS referenzen und langen Pfaden recht Performanceintensiv. 
Aber eine getAsArray Methode  rn_base configurations Objekt fände ich gut.

bzw: Kommentare von unterwegs mit Smartphone aus schreiben ist suboptimal.

**Comment by RocKordier** [comment]
oh ja, stimmt hatte ich vergessen, natuerlich versuche ich via `.` auf ein array zuzugreifen.

Wenn das ein 'Feature' ist, dann sollte wenigstens die PHPdocs richtig sein. Und ja du hast recht die `getExploded` function macht es augenscheinlich richtig, aber falls da doch mal von `get()` aus irgendwelchen Gruenden ein String zurueck kommt laufe ich wieder in einen Error.

`getAsArray` die dir ein Array garantiert wuerde ich auch unterstuetzen!

**Comment by rengaw83** [comment]
`getExploded` macht aktuell genau was du brauchst, es wird dir in jedem Fall ein Array geliefert.

Hier noch ein Beispiel, bei dem Explizit darauf geprüft wird, ob die Konfiguration da ist:
https://github.com/digedag/rn_base/blob/master/filter/class.tx_rnbase_filter_BaseFilter.php#L225
Sobald `get` hier ein Array liefert, wird der PageBrowser behandelt. Kommt `NULL` wird nix gemacht.

Also entweder die `getExploded` nutzen oder refactoren.
Aber zumindest der PHPDoc der `get` Methode muss angepasst werden.
