### ISSUE TITLE
Use the TYPO3/Composer autoloaders

### ISSUE THREAD

**Issue by oliverklee** [digedag/rn_base#50]
1. add an ext_autoload.php for all classes of this extensions (for TYPO3 < 6.2)
2. add an autoload.classmap entry to the ext_emconf.php (for TYPO3 >= 6.2)
3. add an autoload.classmap entry to the composer.json (for TYPO3 >= 6.2)
4. drop all require/require_once/include/include_once calls for class files and all calls to tx_rnbase::load

This will make the code both faster and more readable.

**Comment by digedag** [comment]
Closed as obsolete.
