### ISSUE TITLE
Notice: Undefined variable: TYPO3_CONF_VARS 

### ISSUE THREAD

**Issue by mbrodala** [digedag/rn_base#55]
Installing this extension on a TYPO3 6.2 instance yields many notices like this:

> Notice: Undefined variable: TYPO3_CONF_VARS in /.../typo3conf/ext/rn_base/class.tx_rnbase.php on line 396

This is caused by the XCLASS snippet at the end of all files which should be simply dropped. This reduces the compatibility to TYPO3 4.5 but that should not be an issue anymore. ;-)

**Comment by oliverklee** [comment]
According to https://github.com/DMKEBUSINESSGMBH/typo3-mkforms/pull/15 , mkforms, rn_base and mklib need to keep the old XCLASS footers as long as these extensions need to support TYPO3 CMS 4.5.

We could and should change the TYPO3_CONF_VARS to $GLOBALS['TYPO3_CONF_VARS'], though.

**Comment by mbrodala** [comment]
I tried that first and got this instead:

> Notice: Undefined index: TYPO3_CONF_VARS in /.../typo3conf/ext/rn_base/class.tx_rnbase.php on line 396

Thus my suggestion to drop it completely.

**Comment by mbrodala** [comment]
One option could be to branch of the current version in an 1.x branch and make a new release 2.0.0 which only supports 6.2 and up.

**Comment by oliverklee** [comment]
This would mean that users of old TYPO3 version probably won't get any new features (which I personally find completely okay - if they decide to use such an old version, they can expect to face some downsides in addition to the security implications).

**Comment by oliverklee** [comment]
(I do the same for my extensions.)

**Comment by oliverklee** [comment]
I thinks this was fixed in 32f42893e5b5ad53bcb640fb69ec7df8a79ca8cd.
