### ISSUE TITLE
Public Zugriff auf Instanzvariablen von configurations

### ISSUE THREAD

**Issue by digedag** [digedag/rn_base#62]
Durch den PullRequest #54 wurden viele Instanzvariablen von tx_rnbase_configurations auf private gesetzt. Vor allem cObj ist kritisch, da es von vielen Extensions direkt aufgerufen wird. Dieser Weg ist ja bei cObj auch quasi "Standard" in TYPO3.

Da vermehrt Fehler beim Update aufgetreten sind, sollte diese Variable wieder public gesetzt werden.
Bei anderen Variablen, bin ich da eher skeptisch. Alles was mit einem Unterstrich beginnt, ist ja schon immer absehbar protected. Hier sind auch meiner Ansicht nach, nicht so viele Extensions betroffen.

**Comment by oliverklee** [comment]
Für cObj gibt es einen Getter, den man stattdessen benutzen sollte: https://github.com/digedag/cfc_league_fe/commit/f077676c66f18c9aef2cd81334f430f1696d397a

**Comment by digedag** [comment]
Ja das sollten sie natürlich. Aber es sind eine ganze Menge Extensions im Umlauf, die wir jetzt nicht sofort aktualisieren können/wollen. Und die laufen beim nächsten Update von rn_base sofort in einen FatalError...
