### ISSUE TITLE
Zwei interne Arrays für cObj in configurations

### ISSUE THREAD

**Issue by digedag** [digedag/rn_base#63]
Mir ist aufgefallen, daß es [zwei Arrays für cObj Instanzen](https://github.com/digedag/rn_base/blob/fd77ef784a5f2a8ff9f29215c895425b682624d4/class.tx_rnbase_configurations.php#L127-L137) in rn_base_configurations gibt.
Das ist nicht nur unnötig, sondern vermutlich auch buggy. Die Arrays werden immer schön abwechselnd verwendet.
Das fällt jetzt erst richtig auf, weil @oliverklee die vorher nicht deklarierte Variable $cObjs beim Aufräumen des Codes mit deklariert hat.

**Comment by oliverklee** [comment]
Super, danke!
