### ISSUE TITLE
Usage of $GLOBALS['typo3CacheFactory'] are deprecated

### ISSUE THREAD

**Issue by chhofmann** [digedag/rn_base#66]
`Usage of $GLOBALS['typo3CacheManager'] and $GLOBALS['typo3CacheFactory'] are deprecated since 6.2 will be removed in two versions. Use \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Core\Cache\CacheFactory') or dependency injection to access the singletons.`
Should be refactored.

**Comment by rengaw83** [comment]
Already fixed in #34.
