### ISSUE TITLE
Support for PHP7

### ISSUE THREAD

**Issue by Huaba** [digedag/rn_base#72]
Hi,

newer systems use PHP7 for better performance. I had to use a TYPO3 extension that requires rn_base on a server with PHP7.

Is support for PHP7 planned?

Greets
Huaba

**Comment by digedag** [comment]
Did you get any errors using PHP7? I'm not aware about any problems running rn_base with PHP7.

**Comment by Huaba** [comment]
I'm not sure (don't see errors, but don't tested in detail), but installation via Composer needs the alias hack to work.

composer.json:

`"require": {
  "php": "7.0.8 as 5.6.25"
}
`

But this means, that it only installs on php 7.0.8. If you've different php 7 versions (e.g. 7.0.8 local and 7.0.6 on the server) it won't install.

If no errors in php7 it would be great to change the ext_emconf.php and set

`	'constraints' => array(
		'depends' => array(
			'php' => '5.3.9-5.6.99'
		),
`

to 5.3.9-7.0.99 :)

**Comment by Huaba** [comment]
Great! Thx for your support!

**Comment by Huaba** [comment]
Could you push this version to typo3 ter? Thanks :)

**Comment by digedag** [comment]
Not really within the next few days (weeks)... There was a code cleanup #54 recently that will cause errors in some TER extensions. So I have to update these extensions before I can push rn_base to TER again.

**Comment by Huaba** [comment]
No Problem, i'll use the github repo in composer.

Thx
