### ISSUE TITLE
TYPO3 TER Update

### ISSUE THREAD

**Issue by madaxel** [digedag/rn_base#77]
Is a TER release planned? currently Version 1.0.9 is not working with T3 v 7.6.

After installation i get the error that in rn_base/mod/class.tx_rnbase_mod_BaseModule.php on line 34 includeLLFile() cannot on be called on null Object.

Version 1.1.12 from todays master seems to work.

**Comment by digedag** [comment]
Good point. I will upload the current version before christmas! :christmas_tree: :smile:

**Comment by digedag** [comment]
Released in TER as version 1.2.0.
