### ISSUE TITLE
PHP Error in Classes/Backend/Utility.php line 55 

### ISSUE THREAD

**Issue by stemeda** [digedag/rn_base#86]
I get this error message:

Core: Error handler (BE): PHP Warning: Parameter 2 to TYPO3\CMS\Backend\Utility\BackendUtility::fixVersioningPid() expected to be a reference, value given in .../typo3conf/ext/rn_base/Classes/Backend/Utility.php line 55 

Typo3 7.6 and latest version of rn_base from github

**Comment by rengaw83** [comment]
Hi,
can you check if the fix works for you?
If not, can you post the trace or at least the extension name, which calls the mentioned method on?
Tanks

**Comment by stemeda** [comment]
I've updated `rn_base`. If I get a trace I'll post it, but at the moment I do not know how to reproduce the error. I found it very often in my logs. The method should be called somewhere from `cfc_league'. Additionally I got this error very often, too:

Core: Error handler (BE): PHP Warning: Parameter 2 to TYPO3\CMS\Backend\Utility\BackendUtility::workspaceOL() expected to be a reference, value given in .../typo3conf/ext/rn_base/Classes/Backend/Utility.php line 55

**Comment by rengaw83** [comment]
Thank you for reporting, the workspaceOL method was fixed.
Can you check if the fix works for you?
I am not sure, but i think the error happens on creating a team in the backend module of the `cfc_league` extension.

**Comment by stemeda** [comment]
I updated `rn_base` angain and created a new team. I got 3 errors in log:

```Core: Error handler (BE): PHP Warning: Declaration of tx_cfcleague_models_TeamNoteType::getInstance($uid) should be compatible with tx_rnbase_model_data::getInstance($data = NULL) in .../typo3conf/ext/cfc_league/models/class.tx_cfcleague_models_TeamNoteType.php line 0 ```

```Core: Error handler (BE): PHP Warning: Parameter 2 to TYPO3\CMS\Backend\Utility\BackendUtility::workspaceOL() expected to be a reference, value given in .../typo3conf/ext/rn_base/Classes/Backend/Utility.php line 54 ```

```Core: Error handler (BE): PHP Warning: Parameter 2 to TYPO3\CMS\Backend\Utility\BackendUtility::workspaceOL() expected to be a reference, value given in .../typo3conf/ext/rn_base/Classes/Backend/Utility.php line 54 ```

I also can report the first error in `cfc_league`, too, if you need it :-)

**Comment by rengaw83** [comment]
You are shure, you have updatet `rn_base` to the current dev-master? 
There are currently no new release and the `workspaceOL` call should be performed at line 133 after an update, not line 54. See 69a14e0.

For the first error, please create an new issue at [digedag/cfc_league](https://github.com/digedag/cfc_league/issues),  thanks.

**Comment by stemeda** [comment]
I additionally cleared all caches in install tool. The errors did not happen again. thanks for your help!
