### ISSUE TITLE
TablesTest fails from TYPO3 7.6

### ISSUE THREAD

**Issue by mario-seidel** [digedag/rn_base#87]
Due [this](https://github.com/digedag/rn_base/commit/72a55fdaf84ea9a16cd4e4efe6e2a897322341ed#diff-bcc9bbf192b35d0f30f57e5be0628496) change the test fails from TYPO3 version 7.6
```
1) Tx_Rnbase_Backend_Utility_TablesTest::testPrepareTable
     [exec] Unexpected title
     [exec] Failed asserting that '<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-document-info" data-identifier="actions-document-info">
     [exec] 	<span class="icon-markup">
     [exec] <img src="typo3/sysext/core/Resources/Public/Icons/T3Icons/actions/actions-document-info.svg" width="16" height="16" />
     [exec] 	</span>
     [exec] 	
     [exec] </span>' contains "Info: XX".
```

**Comment by rengaw83** [comment]
The rendering of the title for the image is wrong.
The rendering should  be fixed, not the unittests!
Fixed in [7beac64](https://github.com/digedag/rn_base/commit/7beac649bffdfba1c533f3081448d1efa9542349#diff-bcc9bbf192b35d0f30f57e5be0628496)
